AWSTemplateFormatVersion: '2010-09-09'
Description: Optimistic Bearings Application
Globals:
  Function:
    Environment:
      Variables:
        DeployBucket: opbearbe-deploy
    Runtime: python3.6
    Timeout: 20
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: OBApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/v2
  CognitoIdentityPool:
    Description: Cognito Identity Pool
    Value:
      Ref: OBCognitoIdPool
  CognitoUserPool:
    Description: Cognito User Pool
    Value:
      Ref: OBCognitoUserPool
  CognitoUserPoolClient:
    Description: Cognito User Pool App
    Value:
      Ref: OBCognitoUserPoolClient
  DDB:
    Description: DynamoDB Test Table
    Value:
      Ref: OBListsTableTest
  LamdbaFunction:
    Description: Lambda Function
    Value:
      Ref: OBLambdaSetup
  OBCognitoIdPoolAuthedRoleOutput:
    Description: Cognito Identity Pool IAM Authed Role
    Value:
      Ref: OBCognitoIdPoolAuthedRole
  RestApiId:
    Description: API Gateway API ID
    Value:
      Ref: OBApi
Parameters:
  LambdaFunctionNameValue:
    AllowedValues:
    - setuplambda
    Default: setuplambda
    Description: Lambda Name
    Type: String
  LambdaFunctionProdVersionValue:
    Default: $LATEST
    Description: Lambda Prod Version "Number".  Used in CF template to point lambda
      version, manage env specific env vars.  Typed as string to allow for special
      "$LATEST" version.
    Type: String
Resources:
  OBApi:
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://opbearbe-deploy/swagger.json
      StageName: v1
    Type: AWS::Serverless::Api
  OBCognitoIdPool:
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
      - ClientId:
          Ref: OBCognitoUserPoolClient
        ProviderName:
          Fn::GetAtt:
          - OBCognitoUserPool
          - ProviderName
      IdentityPoolName:
        Ref: AWS::StackName
    Type: AWS::Cognito::IdentityPool
  OBCognitoIdPoolAuthedRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr:
              - authenticated
            StringEquals:
              cognito-identity.amazonaws.com:aud:
              - Ref: OBCognitoIdPool
          Effect: Allow
          Principal:
            Federated:
            - cognito-identity.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: execute-api:Invoke
            Effect: Allow
            Resource:
            - Fn::Join:
              - /
              - - Fn::Join:
                  - ':'
                  - - arn:aws:execute-api
                    - Ref: AWS::Region
                    - Ref: AWS::AccountId
                    - Ref: OBApi
                - '*/GET/*'
            - Fn::Join:
              - /
              - - Fn::Join:
                  - ':'
                  - - arn:aws:execute-api
                    - Ref: AWS::Region
                    - Ref: AWS::AccountId
                    - Ref: OBApi
                - '*/POST/*'
            - Fn::Join:
              - /
              - - Fn::Join:
                  - ':'
                  - - arn:aws:execute-api
                    - Ref: AWS::Region
                    - Ref: AWS::AccountId
                    - Ref: OBApi
                - '*/DELETE/*'
          - Action:
            - mobileanalytics:PutEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: OBCognitoIdPoolAuthedPolicy
    Type: AWS::IAM::Role
  OBCognitoIdPoolAuthedRoleAttach:
    Properties:
      IdentityPoolId:
        Ref: OBCognitoIdPool
      Roles:
        authenticated:
          Fn::GetAtt:
          - OBCognitoIdPoolAuthedRole
          - Arn
    Type: AWS::Cognito::IdentityPoolRoleAttachment
  OBCognitoUserPool:
    Properties:
      AutoVerifiedAttributes:
      - email
      Schema:
      - AttributeDataType: String
        Mutable: true
        Name: name
        Required: false
      - AttributeDataType: String
        Mutable: false
        Name: email
        Required: true
      - AttributeDataType: String
        Mutable: false
        Name: phone_number
        Required: false
      UserPoolName: OBCogUP
    Type: AWS::Cognito::UserPool
  OBCognitoUserPoolClient:
    Properties:
      ClientName: myApp
      GenerateSecret: false
      UserPoolId:
        Ref: OBCognitoUserPool
    Type: AWS::Cognito::UserPoolClient
  OBDeployment:
    Properties:
      Description: My OB deployment
      RestApiId:
        Ref: OBApi
      StageName: DummyStage
    Type: AWS::ApiGateway::Deployment
  OBLambdaSetup:
    Properties:
      CodeUri: s3://opbearbe-deploy/72bb0d375e02fad51dc73f27a4bf48c1
      Environment:
        Variables:
          TABLE_NAME:
            Ref: OBListsTableProd
      Events:
        ProxyApiProdSetupListByIdDelete:
          Properties:
            Method: DELETE
            Path: /setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiProdSetupListByIdGet:
          Properties:
            Method: GET
            Path: /setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiProdSetupListByIdPut:
          Properties:
            Method: PUT
            Path: /setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiProdSetupListGet:
          Properties:
            Method: GET
            Path: /setup/list
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiProdSetupListPost:
          Properties:
            Method: POST
            Path: /setup/list
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiTestSetupListByIdDelete:
          Properties:
            Method: DELETE
            Path: /test/setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiTestSetupListByIdGet:
          Properties:
            Method: GET
            Path: /test/setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiTestSetupListByIdPut:
          Properties:
            Method: PUT
            Path: /test/setup/list/{listid}
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiTestSetupListGet:
          Properties:
            Method: GET
            Path: /test/setup/list
            RestApiId:
              Ref: OBApi
          Type: Api
        ProxyApiTestSetupListPost:
          Properties:
            Method: POST
            Path: /test/setup/list
            RestApiId:
              Ref: OBApi
          Type: Api
      FunctionName:
        Ref: LambdaFunctionNameValue
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  OBLambdaSetupInvokePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: setuplambda:prod
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: OBApi
          - /*/*/*/*
    Type: AWS::Lambda::Permission
  OBLambdaSetupProdAlias:
    Properties:
      Description: Prod Lambda Version Link
      FunctionName:
        Ref: OBLambdaSetup
      FunctionVersion:
        Ref: LambdaFunctionProdVersionValue
      Name: prod
    Type: AWS::Lambda::Alias
  OBLambdaVersionRolling:
    Properties:
      Description: Rolling Version For Dev Promotion
      FunctionName:
        Ref: OBLambdaSetup
    Type: AWS::Lambda::Version
  OBListsTableProd:
    Properties:
      AttributeDefinitions:
      - AttributeName: uid
        AttributeType: S
      - AttributeName: listid
        AttributeType: S
      KeySchema:
      - AttributeName: uid
        KeyType: HASH
      - AttributeName: listid
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: prod.2.ob.lists
    Type: AWS::DynamoDB::Table
  OBListsTableTest:
    Properties:
      AttributeDefinitions:
      - AttributeName: uid
        AttributeType: S
      - AttributeName: listid
        AttributeType: S
      KeySchema:
      - AttributeName: uid
        KeyType: HASH
      - AttributeName: listid
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: test.2.ob.lists
    Type: AWS::DynamoDB::Table
  OBStageV2:
    Properties:
      DeploymentId:
        Ref: OBDeployment
      Description: Auth Test Stage
      RestApiId:
        Ref: OBApi
      StageName: v2
    Type: AWS::ApiGateway::Stage
Transform: AWS::Serverless-2016-10-31
